# 1. ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  PORT: "3333"
  POSTGRES_HOST: "postgres-svc"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "bdtech"
---
# 2. Secret
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  POSTGRES_USER: "danilo"
  POSTGRES_PASSWORD: "danilo"
  MERCADO_PAGO_TOKEN: "TEST-2986934127013785-042221-fd19beb63eb9225c3ae626d6800cb09a-166893008"
---
# 3. Serviço do Banco de Dados (Postgres ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
  type: ClusterIP
---
# 4. StatefulSet do Banco de Dados (Postgres)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  replicas: 1
  serviceName: "postgres-svc"
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secrets
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)", "-d", "$(POSTGRES_DB)"]
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
# 5. Serviço da API (NodePort)
apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  type: NodePort
  ports:
    - name: api
      port: 3333
      targetPort: 3333
      nodePort: 30001 # <-- Você define a porta manualmente
    - name: prisma-studio
      port: 5555
      targetPort: 5555
      nodePort: 30002 # <-- Você define a porta manualmente
  selector:
    app: api
---
# 6. Deployment da API (Sua Aplicação) - CORREÇÃO FINAL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      # --- DOIS INIT CONTAINERS ---
      initContainers:
        # 1. Este usa 'busybox' (que tem 'nc') SÓ PARA ESPERAR
        - name: wait-for-postgres
          image: busybox:1.36
          command: [
              "sh",
              "-c",
              "echo 'Esperando pelo banco de dados (postgres-svc) na porta 5432...'; until nc -z postgres-svc 5432; do sleep 1; done; echo 'Banco de dados pronto!'",
            ]
        # 2. Este usa a SUA imagem SÓ PARA A MIGRAÇÃO
        #    (Roda depois que o 'wait-for-postgres' termina)
        - name: run-migration
          image: danilloagt/fiap-payment:latest
          imagePullPolicy: Always
          command: [
              "sh",
              "-c",
              "export DATABASE_URL=\"postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public\"; echo 'Rodando migration...'; npx prisma db push",
            ]
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secrets
      
      # Container principal da API
      containers:
        - name: api
          image: danilloagt/fiap-payment:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
            - containerPort: 5555
          command: [
              "sh",
              "-c",
              "export DATABASE_URL=\"postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public\"; npx tsx src/server.ts",
            ]
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secrets